import {CONFIG,MARKETS,predict} from './model.js';
import {DEFAULTS,pragueDate,isClosed,validateFilters,evaluateOffer,rankOffers,roundModels} from './scanner.js';
const $=id=>document.getElementById(id),fmt=(x,n=2)=>Number.isFinite(x)?x.toLocaleString('cs-CZ',{minimumFractionDigits:n,maximumFractionDigits:n}):'—',pct=x=>fmt(x*100,1)+' %',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,history,metrics,cache=new Map(),offers=new Map();
const getFilters=()=>validateFilters({minProbability:Number($('round-prob').value)/100,minOdds:Number($('round-odds').value)});
function getModels(date){if(!cache.has(date))cache.set(date,roundModels(history,date));return cache.get(date)}
function render(){try{
 const date=$('round-date').value,filters=getFilters();if(!date)return;
 const fs=data.fixtures.filter(f=>f.date===date),closed=fs.filter(f=>isClosed(f)).length;
 if(!fs.length){$('round-summary').innerHTML=`<div class="verdict">${date<data.fixtures[0].date||date>data.fixtures.at(-1).date?'Pro toto datum nemáme rozpis.':'V uloženém rozpisu na tento den není zápas.'}</div><p class="small">Rozpis je uložená kopie, nikoli živý přenos.</p>`;$('round-cards').replaceChildren();return}
 const {models,lastDataDate}=getModels(date);let count=0;
 const cards=fs.map(f=>{
  const analyses=Object.keys(MARKETS).map(m=>{const over=predict(models[m],f.home,f.away,CONFIG.lines[m],'over');return over.p>=.5?over:predict(models[m],f.home,f.away,CONFIG.lines[m],'under')});
  const evaluated=rankOffers((offers.get(f.id)??[]).map(o=>evaluateOffer(models[o.market],f,o,metrics,filters,Date.now(),lastDataDate)));
  const candidate=evaluated.find(r=>r.eligible);if(candidate)count++;
  const ended=isClosed(f),status=ended?'Zápas uzavřen':candidate?'Kandidát k ověření':evaluated.length?'Nesázet podle zadaných nabídek':'Chybí skutečné kurzy';
  const reason=ended?'Zobrazená analýza používá jen dřívější zápasy. Nejde o aktuální sázkovou příležitost.':candidate?`${candidate.side==='over'?'Over':'Under'} ${fmt(candidate.line,1)} ${MARKETS[candidate.market].label.toLowerCase()} · kurz ${fmt(candidate.offer.odds)} · odhad ${pct(candidate.p)}. Zdroj ceny: ručně zadaný kurz.`:evaluated.length?'Žádná vložená nabídka neprošla současně filtrem šance, kurzu, nejistoty a kvality podkladů.':'Níže je odhad pro pevné testovací hranice. Neznamená to, že je Tipsport právě nabízí.';
  return `<article class="panel game-card" data-game="${f.id}"><div class="game-header"><div><p class="eyebrow">${f.round}. KOLO · ${f.completed?'DOHRÁNO':esc(f.time??'ČAS NEPOTVRZEN')} · <a href="${esc(f.source)}" target="_blank" rel="noreferrer">Zápis ↗</a></p><h2>${esc(f.homeName)} <span class="muted">×</span> ${esc(f.awayName)}</h2></div><span class="pill ${candidate?'candidate':''}">${status}</span></div><p class="round-reason">${esc(reason)}</p><div class="table-wrap"><table><thead><tr><th>Co model čeká</th><th>Pravděpodobnější strana</th><th>Šance</th><th>Férový kurz</th><th>Kurz s rezervou od</th><th>Opora v datech</th></tr></thead><tbody>${analyses.map(r=>`<tr><td>${esc(MARKETS[r.market].label)} <span class="small">${r.market==='penalties'?'celý zápas':'60 min'}</span></td><td>${r.side==='over'?'Over':'Under'} ${fmt(r.line,1)}</td><td>${pct(r.p)}</td><td>${fmt(r.fair)}</td><td>${fmt(Math.max(r.buffered,filters.minOdds))}</td><td>${r.market==='shots'?'Předběžná':r.market==='goals'?'Jen orientační':'Neověřená definice'}</td></tr>`).join('')}</tbody></table></div><p class="small">Kurz s rezervou zohledňuje spodní odhad a 5% modelovou rezervu. Vyšší šance a vysoký kurz se nemusí současně najít. Data do ${lastDataDate}.</p>${ended?'':`<details class="offer-details"><summary>Doplnit skutečnou nabídku Tipsportu</summary><form class="offer-form" data-fixture="${f.id}"><label>Trh<select name="market"><option value="shots">Střely · 60 min</option><option value="goals">Góly · 60 min</option><option value="penalties">Vyloučení · experiment</option></select></label><label>Strana<select name="side"><option value="over">Over</option><option value="under">Under</option></select></label><label>Hranice<input name="line" type="number" min="0.5" max="149.5" step="1" value="55.5" required></label><label>Kurz Tipsportu<input name="odds" type="number" min="1.01" max="1000" step="0.01" placeholder="např. 1,95" required></label><label class="offer-check"><input name="rules" type="checkbox" required> Ověřil jsem právě teď kurz a shodu definice trhu.</label><button class="secondary" type="submit">Porovnat nabídku</button></form><p class="small">Nabídky zůstávají jen po dobu otevření stránky. Za 15 minut se označí jako neaktuální. <a href="https://www.tipsport.cz/kurzy/ledni-hokej/ledni-hokej-muzi/ceska-tipsport-extraliga-2174" target="_blank" rel="noreferrer">Otevřít Tipsport ↗</a></p></details>`}${evaluated.length?`<div class="offer-results">${evaluated.map(r=>`<div class="verdict ${r.eligible?'good':''}"><strong>${r.side==='over'?'Over':'Under'} ${fmt(r.line,1)} · ${esc(MARKETS[r.market].label)} · kurz ${fmt(r.offer.odds)}</strong><br>Šance ${pct(r.p)} · bodová výhoda ${r.ev>=0?'+':''}${pct(r.ev)} · výhoda po rezervě ${pct(r.conservativeEV)}<br><span class="small">${r.eligible?'Kandidát k ověření, nikoli jistá sázka.':esc(r.reasons.join(' '))} Záznam ${new Date(r.offer.observedAt).toLocaleTimeString('cs-CZ')}.</span></div>`).join('')}</div>`:''}</article>`;
 });
 $('round-summary').innerHTML=`<div class="round-totals"><span><strong>${fs.length}</strong> zápasů</span><span><strong>${count}</strong> kandidátů z doplněných kurzů</span><span><strong>${closed}</strong> uzavřených zápasů</span></div><div class="verdict warn">Načtené kurzy PulseScore najdeš v záložce Načtené kurzy. Tento přehled vyhodnocuje ručně doplněné nabídky. Rozpis a statistiky jsou snapshot z ${new Date(data.retrievedAt).toLocaleString('cs-CZ')}; Server obnovuje rozpis a kontrolované statistiky nejvýše jednou za šest hodin při otevřeném webu. Bez doložené ceny nevydáváme konkrétní doporučení.</div>${closed===fs.length?'<p class="small">Dnešní zápasy jsou dohrané. Přepni na nejbližší další hrací den pro přípravu dalšího kola.</p>':''}`;
 $('round-cards').innerHTML=cards.join('');
 for(const form of document.querySelectorAll('.offer-form')){form.querySelector('[name=market]').addEventListener('change',e=>{form.elements.line.value=CONFIG.lines[e.target.value]});form.addEventListener('submit',e=>{e.preventDefault();try{const o={market:form.elements.market.value,side:form.elements.side.value,line:Number(form.elements.line.value),odds:Number(form.elements.odds.value),rulesConfirmed:form.elements.rules.checked,observedAt:new Date().toISOString(),source:'manual-tipsport'};const f=fs.find(g=>g.id===form.dataset.fixture);evaluateOffer(models[o.market],f,o,metrics,filters,Date.now(),lastDataDate);const list=offers.get(f.id)??[];offers.set(f.id,[...list.filter(q=>!(q.market===o.market&&q.side===o.side&&q.line===o.line)),o]);render()}catch(err){alert(err.message)}})}
}catch(e){$('round-summary').innerHTML=`<div class="verdict warn">${esc(e.message)}</div>`;$('round-cards').replaceChildren()}}
async function init(){try{const [d,h,b]=await Promise.all(['rounds','history','backtest'].map(async name=>{const r=await fetch(`data/${name}.json`);if(!r.ok)throw Error('Rozpis se nepodařilo načíst.');return r.json()}));data=d;history=[...h.games,...d.games].sort((a,b)=>a.date.localeCompare(b.date));metrics=b.metrics;
 const loadCurrent=async()=>{try{const r=await fetch('unavailable-server');if(!r.ok)return;const state=await r.json();data=state.rounds;history=[...new Map([...h.games,...data.games].map(g=>[g.id,g])).values()];cache.clear();render();}catch{}};
 window.addEventListener('statistics-updated',loadCurrent);await loadCurrent();$('round-date').value=pragueDate();for(const id of ['round-date','round-prob','round-odds'])$(id).addEventListener('change',render);$('round-today').addEventListener('click',()=>{$('round-date').value=pragueDate();render()});$('round-next').addEventListener('click',()=>{const next=data.fixtures.find(f=>f.date>pragueDate()&&!f.completed);if(next){$('round-date').value=next.date;render()}});render();setInterval(()=>{if(offers.size)render()},60000)}catch(e){$('round-summary').textContent=e.message}}
init();
